insert into TBLMDL (MDLCODE, PMDLCODE, MDLVER, MDLTYPE, MDLSTATUS, MDLDESC, MDLSEQ, MDLHFNAME, MUSER, MDATE, MTIME, ISSYS, ISACTIVE, FORMURL, EATTRIBUTE1, ISRESTRAIN)
values ('MO2RCARDLINK', 'CS_DATACOLLECT', '1', 'C/S', 'Alpha', '工单产品序列号打印', 55, '', 'ADMIN', 20110723, 141122, '1', '1', 'BenQGuru.eMES.Client.FMoCodeRCardLink', '', '0');


insert into TBLMENU (MENUCODE, MDLCODE, PMENUCODE, MENUDESC, MENUSEQ, MENUTYPE, MUSER, MDATE, MTIME, EATTRIBUTE1, VISIBILITY)
values ('CS_MO2RCARDLINK', 'MO2RCARDLINK', 'CS_DATACOLLECT', '工单序列号打印', 55, 'C/S', 'ADMIN', 20110723, 141243, '', '0');
