//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace BenQGuru.eMES.WinCeClient.MaterialOnShelves {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaterialOnShelvesSoap", Namespace="http://tempuri.org/")]
    public partial class MaterialOnShelves : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public MaterialOnShelves() {
            this.Url = "http://112.74.38.84/mestest/BenQGuru.eMES.Web.WebService/MaterialOnShelves.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActOnShelvesQTY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetActOnShelvesQTY(string CartonNo) {
            object[] results = this.Invoke("GetActOnShelvesQTY", new object[] {
                        CartonNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetActOnShelvesQTY(string CartonNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetActOnShelvesQTY", new object[] {
                        CartonNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetActOnShelvesQTY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPlanOnShelvesQTY", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPlanOnShelvesQTY(string CartonNo) {
            object[] results = this.Invoke("GetPlanOnShelvesQTY", new object[] {
                        CartonNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPlanOnShelvesQTY(string CartonNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPlanOnShelvesQTY", new object[] {
                        CartonNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPlanOnShelvesQTY(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCUSMcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCUSMcode(string CartonNo) {
            object[] results = this.Invoke("GetCUSMcode", new object[] {
                        CartonNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCUSMcode(string CartonNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCUSMcode", new object[] {
                        CartonNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetCUSMcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataGrid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataGrid(string CartonNo, string LocationNo) {
            object[] results = this.Invoke("GetDataGrid", new object[] {
                        CartonNo,
                        LocationNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataGrid(string CartonNo, string LocationNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataGrid", new object[] {
                        CartonNo,
                        LocationNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetDataGrid(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDataTable() {
            object[] results = this.Invoke("GetDataTable", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataTable(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataTable", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndGetDataTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Retrieve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Retrieve(string cartonNO) {
            object[] results = this.Invoke("Retrieve", new object[] {
                        cartonNO});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRetrieve(string cartonNO, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Retrieve", new object[] {
                        cartonNO}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndRetrieve(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnShelves", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OnShelves(System.Data.DataTable dt, string cartonNO, string locationNo, string UserCode) {
            object[] results = this.Invoke("OnShelves", new object[] {
                        dt,
                        cartonNO,
                        locationNo,
                        UserCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOnShelves(System.Data.DataTable dt, string cartonNO, string locationNo, string UserCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OnShelves", new object[] {
                        dt,
                        cartonNO,
                        locationNo,
                        UserCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOnShelves(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
