//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Alert {
    
    public partial class FAlertLinePauseMP {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.Label lblTitle;
        protected System.Web.UI.WebControls.Label lblAlertItemSequence;
        protected System.Web.UI.WebControls.TextBox txtAlertItemSequence;
        protected System.Web.UI.WebControls.Label lblAlertItemDesc;
        protected System.Web.UI.WebControls.TextBox txtAlertItemDesc;
        protected System.Web.UI.WebControls.Label lblAlertLinePause;
        protected System.Web.UI.WebControls.Label lblSSEdit;
        protected BenQGuru.eMES.Web.SelectQuery.SelectableTextBox4SS txtSSCodeWhere;
        protected System.Web.UI.WebControls.Label lblAlertOPCode;
        protected System.Web.UI.WebControls.DropDownList ddlOPCode;
        protected System.Web.UI.WebControls.Label lblAlertStandard;
        protected System.Web.UI.WebControls.TextBox txtAlertStandard;
        protected System.Web.UI.WebControls.Label lblDealMethod;
        protected System.Web.UI.WebControls.CheckBox chbGenerateNotice;
        protected System.Web.UI.WebControls.CheckBox chbSendMail;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit cmdMailSetup;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit cmdSave;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit cmdReturn;
    }
}
