//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5485 版自动生成。
// 
namespace BenQGuru.eMES.WinCeClient.LocStorTrans {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LocStorTransSoap", Namespace="http://tempuri.org/")]
    public partial class LocStorTrans : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public LocStorTrans() {
            this.Url = "http://localhost/TDTech/BenQGuru.eMES.Web.WebService/LocStorTrans.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateAutoDocmentsNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateAutoDocmentsNo() {
            object[] results = this.Invoke("CreateAutoDocmentsNo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateAutoDocmentsNo(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateAutoDocmentsNo", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCreateAutoDocmentsNo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Add", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Add(string userCode, string newIqcNo, string fromCarton) {
            object[] results = this.Invoke("Add", new object[] {
                        userCode,
                        newIqcNo,
                        fromCarton});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAdd(string userCode, string newIqcNo, string fromCarton, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Add", new object[] {
                        userCode,
                        newIqcNo,
                        fromCarton}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAdd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDqmCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDqmCode(string fromCarton) {
            object[] results = this.Invoke("GetDqmCode", new object[] {
                        fromCarton});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDqmCode(string fromCarton, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDqmCode", new object[] {
                        fromCarton}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetDqmCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Commit_Click", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Commit_Click(string userCode, string statusList, string transNo, string tLocationCode, string fromCarton, string tcarton, string inputsn, string inputqty) {
            object[] results = this.Invoke("Commit_Click", new object[] {
                        userCode,
                        statusList,
                        transNo,
                        tLocationCode,
                        fromCarton,
                        tcarton,
                        inputsn,
                        inputqty});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCommit_Click(string userCode, string statusList, string transNo, string tLocationCode, string fromCarton, string tcarton, string inputsn, string inputqty, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Commit_Click", new object[] {
                        userCode,
                        statusList,
                        transNo,
                        tLocationCode,
                        fromCarton,
                        tcarton,
                        inputsn,
                        inputqty}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndCommit_Click(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LocStorTransView", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LocStorTransView(string transNo, string dqmCode, string fromCartonno, string locationCode, string cartonno) {
            object[] results = this.Invoke("LocStorTransView", new object[] {
                        transNo,
                        dqmCode,
                        fromCartonno,
                        locationCode,
                        cartonno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLocStorTransView(string transNo, string dqmCode, string fromCartonno, string locationCode, string cartonno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LocStorTransView", new object[] {
                        transNo,
                        dqmCode,
                        fromCartonno,
                        locationCode,
                        cartonno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable EndLocStorTransView(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
}
